import_name: 'ArkanaKeys' # Optional. Name of the framework to be imported. Defaults to ArkanaKeys.
namespace: 'Keys' # Optional. Namespace used to access the secrets in the codebase. Defaults to ArkanaKeys.
result_path: 'ArkanaKeys' # Optional. Destination path of the generated code, related to the path of this config file. Defaults to ArkanaKeys.
swift_declaration_strategy: let # Optional. One of: lazy var, var, let. Defaults to let.
should_generate_unit_tests: true # Optional. One of: true, false. Defaults to true.
package_manager: spm # Optional. This setting defines which type of dependency management you're going ot use to integrate Arkana into your project. One of: spm, cocoapods. If you use both in your project, use cocoapods here. Defaults to spm.
global_secrets: # Optional. List of secrets that are the same regardless of which environment is being built. Defaults to empty.
  - tmdbApiKey
